function f = Showlayout(RT,hPanel)
	% ShowLayout(hPanel) - Show a default GUI of Z812 attenuator. hPanel can be handle of uipanel. If omitted, a new figure will be created.
	if ~exist('hPanel')
		hPanel = figure('Visible','off','Position',[0,0,256,192]);
	end
	hRotateto_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Rotate to:',...
				'Position',[0.075,0.8,0.4,0.1]);
	hRotateto_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.8,0.4,0.1],...
				'Callback',{@RotatetoCallback});
	hRotateby_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Rotate by:',...
				'Position',[0.075,0.6,0.4,0.1]);
	hRotateby_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.6,0.4,0.1],...
				'Callback',{@RotatebyCallback});
	hSpeed_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Set speed:',...
				'Position',[0.075,0.4,0.4,0.1]);
	hSpeed_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.4,0.4,0.1],...
				'Callback',{@SpeedCallback});
	hCurrentposition_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Position Now:',...
				'Position',[0.075,0.2,0.4,0.1]);
	hCurrentposition = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.2,0.4,0.1]);
	hGohome = uicontrol(hPanel,'Style','pushbutton',...
				'Unit','Normalize',...
				'String','Go Home',...
				'Position',[0.075,0.05,0.4,0.1],...
				'Callback',{@GohomeCallback});
	hConnect = uicontrol(hPanel,'Style','pushbutton',...
				'Unit','Normalize',...
				'String','Connect',...
				'Position',[0.525,0.05,0.4,0.1],...
				'Callback',{@ConnectCallback});
	movegui(hPanel,'center');
	set(hPanel,'Visible','on');

	lh = event.listener(RT,'eRTThorlabsCR1Z7PositionChanged',@PositionChanged);
	lh.Enabled = false;

	function GohomeCallback(hObject,eventdata)
		RT.Gohome;
	end
	function ConnectCallback(hObject,eventdata)
		if (RT.connected)
			RT.Disconnect;
			set(hConnect,'String','Connect');
            RT.connected = false;
			lh.Enabled = false;
		else
			RT.Connect;
			set(hConnect,'String','Disconnect');
			lh.Enabled = true;
            RT.connected = true;
		end
	end
	function SpeedCallback(hObject,eventdata)
		speed = str2num(get(hSpeed_edit,'String'));
		RT.Setspeed(speed);
	end
	function RotatebyCallback(hObject,eventdata)
		Pos = str2num(get(hRotateby_edit,'String'));
		RT.Rotateby(Pos);
	end
	function RotatetoCallback(hObject,eventdata)
		Pos = str2num(get(hRotateto_edit,'String'));
		RT.Rotateto(Pos);
	end
	function PositionChanged(hObject,eventdata)
		set(hCurrentposition,'String',num2str(RT.currentPosition));
	end
end
