function f = ShowLayout(LI,hPanel)
	if (~exist('hPanel'))
		hPanel = figure('Position',[0 0 1024 768]);
		movegui(hPanel,'center');
	end
	hCurrent_Start_Text = uicontrol(hPanel,'Style','text',...
                                   'String','Current(mA)   from',...
                                   'Units','Normalized',...
                                   'Position',[0.02,0.9,0.2,0.05]);
	hCurrent_Start_Edit = uicontrol(hPanel,'Style','edit',...
                                   'String','0',...
                                   'Units','Normalized',...
                                   'Position',[0.23,0.9,0.1,0.05]);
	htext1 = uicontrol(hPanel,'Style','text',...
                                   'String','to',...
                                   'Units','Normalized',...
                                   'Position',[0.34,0.9,0.1,0.05]);
	hCurrent_End_Edit = uicontrol(hPanel,'Style','edit',...
       	                           'String','0',...
       	                           'Units','Normalized',...
                                   'Position',[0.45,0.9,0.1,0.05]);
	hCurrent_Step_Text = uicontrol(hPanel,'Style','text',...
                                   'String','Step by',...
                                   'Units','Normalized',...
                                   'Position',[0.56,0.9,0.1,0.05]);
	hCurrent_Step_Edit = uicontrol(hPanel,'Style','edit',...
                                   'String','0',...
                                   'Units','Normalized',...
                                   'Position',[0.67,0.9,0.1,0.05]);
	hContinue_Save_Prefix_Text = uicontrol(hPanel,'Style','text',...
                                         'String','Prefix',...
                                         'Units','Normalized',...
                                         'Position',[0.02,0.83,0.2,0.05]);
	hContinue_Save_Prefix_Edit = uicontrol(hPanel,'Style','edit',...
                                         'String','',...
                                         'Units','Normalized',...
                                         'Position',[0.23,0.83,0.4,0.05]);
	hContinue_Save_Suffix_Text = uicontrol(hPanel,'Style','text',...
                                         'String','Suffix Next:',...
                                         'Units','Normalized',...
                                         'Position',[0.65,0.83,0.1,0.05]);
	hContinue_Save_Suffix_Edit = uicontrol(hPanel,'Style','edit',...
                                         'String','',...
                                         'Units','Normalized',...
                                         'Position',[0.77,0.83,0.1,0.05]);
	hContinue_Measurement_Start = uicontrol(hPanel,...
                                   'Style','pushbutton',...
                                   'String','Start',...
                                   'Units','Normalized',...
                                   'Position',[0.8,0.9,0.15,0.05],...
                                   'CallBack',{@Start_Continue_Measurement});
	hContinue_Measurement_Plot = axes('Parent',hPanel,...
                                  'Units','Normalized',...
                                  'Position',[0.1,0.1,0.8,0.7]);
	xlabel('Current(mA)');ylabel('Light Intensity(W)');
end
