function f = Showlayout(LM,hPanel)
	% ShowLayout(hPanel) - Show a default GUI of Z812 attenuator. hPanel can be handle of uipanel. If omitted, a new figure will be created.
	if ~exist('hPanel')
		hPanel = figure('Visible','off','Position',[0,0,256,192]);
	end
	hMoveto_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Move to:',...
				'Position',[0.075,0.8,0.4,0.1]);
	hMoveto_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.8,0.4,0.1],...
				'Callback',{@MovetoCallback});
	hMoveby_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Move by:',...
				'Position',[0.075,0.6,0.4,0.1]);
	hMoveby_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.6,0.4,0.1],...
				'Callback',{@MovebyCallback});
	hSpeed_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Set speed:',...
				'Position',[0.075,0.4,0.4,0.1]);
	hSpeed_edit = uicontrol(hPanel,'Style','edit',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.4,0.4,0.1],...
				'Callback',{@SpeedCallback});
	hCurrentposition_text = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','Position Now:',...
				'Position',[0.075,0.2,0.4,0.1]);
	hCurrentposition = uicontrol(hPanel,'Style','text',...
				'Unit','Normalize',...
				'String','',...
				'Position',[0.525,0.2,0.4,0.1]);
	hGohome = uicontrol(hPanel,'Style','pushbutton',...
				'Unit','Normalize',...
				'String','Go Home',...
				'Position',[0.075,0.05,0.4,0.1],...
				'Callback',{@GohomeCallback});
	hConnect = uicontrol(hPanel,'Style','pushbutton',...
				'Unit','Normalize',...
				'String','Connect',...
				'Position',[0.525,0.05,0.4,0.1],...
				'Callback',{@ConnectCallback});
	movegui(hPanel,'center');
	set(hPanel,'Visible','on');

	lh = event.listener(LM,'eLMThorlabsZ812PositionChanged',@PositionChanged);
	lh.Enabled = false;

	function GohomeCallback(hObject,eventdata)
		LM.Gohome;
	end
	function ConnectCallback(hObject,eventdata)
		if (LM.connected)
			LM.Disconnect;
			set(hConnect,'String','Connect');
            LM.connected = false;
			lh.Enabled = false;
		else
			LM.Connect;
			set(hConnect,'String','Disconnect');
			lh.Enabled = true;
            LM.connected = true;
		end
	end
	function SpeedCallback(hObject,eventdata)
		speed = str2num(get(hSpeed_edit,'String'));
		LM.Setspeed(speed);
	end
	function MovebyCallback(hObject,eventdata)
		Pos = str2num(get(hMoveby_edit,'String'));
		LM.Moveby(Pos);
	end
	function MovetoCallback(hObject,eventdata)
		Pos = str2num(get(hMoveto_edit,'String'));
		LM.Moveto(Pos);
	end
	function PositionChanged(hObject,eventdata)
		set(hCurrentposition,'String',num2str(LM.currentPosition));
	end
end
